version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201808-01
    environment:
    - NVM_VERSION: 0.33.5
    - NODE_VERSION: 8
    - K8S_VERSION: v1.13.0
    - KUBECONFIG: /home/circleci/.kube/config
    - MINIKUBE_VERSION: v0.32.0
    - MINIKUBE_WANTUPDATENOTIFICATION: false
    - MINIKUBE_WANTREPORTERRORPROMPT: false
    - MINIKUBE_HOME: /home/circleci
    - CHANGE_MINIKUBE_NONE_USER: true
    steps:
    - checkout
    - run:
        name: Install node
        command: |
          set +e
          curl -o- https://raw.githubusercontent.com/creationix/nvm/v${NVM_VERSION}/install.sh | bash
          export NVM_DIR="/opt/circleci/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install ${NODE_VERSION}
          nvm alias default ${NODE_VERSION}
          echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
          echo "[ -s \"$NVM_DIR/nvm.sh\" ] && . \"$NVM_DIR/nvm.sh\"" >> $BASH_ENV
    - run:
        name: Install yarn
        command: |
          curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
          echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
          sudo rm /var/lib/apt/lists/lock
          sudo rm /var/cache/apt/archives/lock
          sudo rm /var/lib/dpkg/lock
          sudo apt-get update
          sudo apt-get install yarn
    - run:
        name: Setup kubectl
        command: |
          curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/${K8S_VERSION}/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
          mkdir -p ${HOME}/.kube
          touch ${HOME}/.kube/config
    - run:
        name: Setup minikube
        command: |
          curl -Lo minikube https://github.com/kubernetes/minikube/releases/download/${MINIKUBE_VERSION}/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
    - run:
        name: Start minikube
        command: |
          sudo -E minikube start --vm-driver=none --cpus 2 --memory 2048 --kubernetes-version=${K8S_VERSION} &> $HOME/minikube.log 2>&1 < /dev/null
    - run:
        name: Wait for minikube
        command: |
          JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}';
          until kubectl get nodes -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do
            sleep 1;
          done
    - run:
        name: Install dependencies
        command: yarn install
    - run:
        name: Run tests
        command: yarn test
workflows:
  version: 2
  workflow:
    jobs:
    - build
